<?php

namespace V2\MainBundle\Repository;

/**
 * BomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BomRepository extends \Doctrine\ORM\EntityRepository
{
}
