<?php

namespace V2\MainBundle\Repository;

/**
 * KittingShortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KittingShortRepository extends \Doctrine\ORM\EntityRepository
{
}
