<?php

namespace V2\MainBundle\Repository;

/**
 * KittingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KittingRepository extends \Doctrine\ORM\EntityRepository
{
}
