<?php

namespace V2\MainBundle\Repository;

/**
 * SchedulingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulingRepository extends \Doctrine\ORM\EntityRepository
{
}
